Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -99,22 +99,38 @@ jobs:
         wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
         tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz
 
-    - name: Download Custom-Clang
-      if: env.USE_CUSTOM_CLANG == 'true'
+    - name: Download Gcc-aosp
+      if: env.USE_CUSTOM_GCC_64 != 'true' && env.USE_CUSTOM_GCC_32 != 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_CLANG_SOURCE }} =~ git ]]; then
-            if [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.tar.gz' ]]; then
-                wget -O clang.tar.gz ${{ env.CUSTOM_CLANG_SOURCE }}
-                mkdir clang-aosp
-                tar -C clang-aosp/ -zxvf clang.tar.gz
-            else
-                git clone ${{ env.CUSTOM_CLANG_SOURCE }} -b ${{ env.CUSTOM_CLANG_BRANCH }} clang-aosp --depth=1
+        if [ ${{ env.ENABLE_GCC_ARM64 }} = true ]; then
+            mkdir -p gcc-64
+            wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+            if [ ! -f gcc-aarch64.tar.gz ] || [ ! -s gcc-aarch64.tar.gz ]; then
+                echo "ERROR: GCC 下载失败"
+                exit 1
             fi
-        else
-            wget -O clang.zip ${{ env.CUSTOM_CLANG_SOURCE }}
-            mkdir clang-aosp
-            unzip clang.zip -d clang-aosp/
+            tar -C gcc-64/ -zxvf gcc-aarch64.tar.gz
+            if [ ! -f gcc-64/bin/aarch64-linux-android-gcc ]; then
+                echo "ERROR: GCC 解压失败，找不到编译器"
+            exit 1
+            fi
+            echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin/aarch64-linux-android-" >> $GITHUB_ENV
+        fi
+
+        if [ ${{ env.ENABLE_GCC_ARM32 }} = true ]; then
+            mkdir -p gcc-32
+            wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+            if [ ! -f gcc-arm.tar.gz ] || [ ! -s gcc-arm.tar.gz ]; then
+                echo "ERROR: ARM32 GCC 下载失败"
+                exit 1
+            fi
+            tar -C gcc-32/ -zxvf gcc-arm.tar.gz
+            if [ ! -f gcc-32/bin/arm-linux-androideabi-gcc ]; then
+                echo "ERROR: ARM32 GCC 解压失败"
+                exit 1
+            fi
+            echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin/arm-linux-androideabi-" >> $GITHUB_ENV
         fi
 
     - name: Download Gcc-aosp
